# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 029cea3b9411bfe514d34c51a545447329209b36b59c1a9e1f0dccc7708537f02c0d40bc33524971e6d859273c49739940c408f5c15ee6323c4b49af85182c71

test:
  secret_key_base: 31b40af7c228d4b9d7be077c47821c3b7d9cb639493946b36d01808c55c3868e5c8c29dc7c865e0cda576698c660432640ba52692f4854806e01fc71ed3e53ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
